server:
  port: 7775

app:
  prop:
    read:
      timeout: 60000

spring:
  h2:
    console:
      enabled: true
#Data Source with Log4JDBC
  datasource:
    url: jdbc:log4jdbc:h2:mem:GS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: net.sf.log4jdbc.DriverSpy
    data-username: sa
    data-password:
#Data Source original
#  datasource:
#    url: jdbc:h2:mem:GS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    data-username: sa
#    data-password:
  jpa:
    properties:
     hibernate:
      enable_lazy_load_no_trans: true
      format_sql: true
#    database-platform: H2
#    show-sql: true